audit_header: false
title: Wasatch Front Real Estate Video Blog with Kody Watts
description: Our mission at The Kody Watts Team is to be your best resource for Wasatch Front real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The The Kody Watts Team, your professional Wasatch Front Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Kody Watts
  title:
  license_number:
  about_markdown: |
    I am dedicated to providing excellent service to my clients. If you’re thinking about buying, selling or investing in real estate, please give me a call. I look forward to discussing your individual needs and providing advice with no obligation to you. My blog is here to help you with tips and tricks as well as keep you updated with important information. If you haven’t registered on my website yet, please take a moment to sign up. Listings are updated daily and I can set you up on personalized new listing emails and price changes that will allow you to stay up to date with the homes in your search criteria. When you are ready, I am here to help you reach your real estate goals.
  market: Wasatch Front
  brand: The Kody Watts Team
  brokerage: Keller Williams South Valley Realty
  address: 4020 W. Daybreak Pkwy Suite 110<br>S. Jordan, UT 84009
  phone: 801-809-0914
  phone_type:
  phone2:
  phone2_type:
  email: kody@kodywattsteam.com
  url: https://www.elitehomesearch.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.elitehomesearch.com/fine/real/estate/marketeval
  second_CTA_text: Home Search
  second_CTA_URL: https://www.elitehomesearch.com/fine/real/estate/newsearch

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "What’s Your Wasatch Front Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://www.elitehomesearch.com/fine/real/estate/marketeval

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a Wasatch Front Home?"
    CTA_text2: "Search the entire MLS for your Wasatch Front home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.elitehomesearch.com/fine/real/estate/newsearch

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url:
  gplus_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Wasatch Front Real Estate Podcast with Kody Watts'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Wasatch Front Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from The Kody Watts Team - your professional Wasatch Front Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Wasatch Front, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Kody Watts'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Wasatch Front Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#404042'
  theme_color: '#000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: white

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
